baseURL = 'https://hvitoi.github.io/vitoi-eng-seguranca/'
title = 'Vitoi - Engenharia de Segurança do Trabalho'
theme = 'hugo-universal-theme'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'

[params]
style = 'red'
logo = 'img/logo.png'
logo_small = 'img/logo.png'

about_us = "<p>Paellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
contact_url = "contact"
copyright = "Copyright (c) 2015 - 2024, YourCompany; all rights reserved."
address = """
            <p class="text-uppercase">
                  <strong>Luiz Henrique Rossi Vitoi</strong>
                  <br>Rua Barão de São João
                  <br>São João Nepomuceno, MG
            </p>
            """

[params.carouselHomepage]
enable = true
auto_play = true
slide_speed = 2000
pagination_speed = 1000

[params.features]
enable = true
cols = 3

[params.testimonials]
enable = true
title = "Depoimentos"
subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.carouselTestimonials]
items = 4
auto_play = false
slide_speed = 2000
pagination_speed = 1000

[params.see_more]
enable = true
icon = "far fa-file-alt"
title = "Quer saber mais?"
subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
link_url = "contact"
link_text = "Veja como entrar em contato"

[params.clients]
enable = true
title = "Nossos Clientes"
subtitle = ""

[params.carouselCustomers]
items = 6
auto_play = false
slide_speed = 2000
pagination_speed = 1000

[params.widgets]

[menu]

[[menu.main]]
identifier = "menu.home"
name = "Início"
url = "/"
weight = 1

[[menu.main]]
identifier = "menu.faq"
name = "FAQ"
url = "/faq/"
weight = 2

[[menu.main]]
identifier = "contact"
name = "Contato"
url = "/contact/"
weight = 3
