baseURL = 'vitoiengenharia.com'
title = 'Vitoi - Engenharia de Segurança do Trabalho'
theme = 'hugo-universal-theme'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'

[params]
style = 'red'
logo = 'img/logo.png'
logo_small = 'img/logo.png'

about_us = "<p>Engenheiro civil e de segurança com 38 anos de experiência, especializado em diversas obras, destaque em projetos de combate a incêndios e comprometido com altos padrões de segurança.</p>"
contact_url = "contact"
copyright = "Copyright (c) 2012 - 2024, Vitoi Engenharia; todos os direitos reservados."
address = """
            <p class="text-uppercase">
                  <strong>Luiz Henrique Rossi Vitoi</strong>
                  <br>Rua Barão de São João, 33
                  <br>São João Nepomuceno, MG
            </p>
            """

[params.carouselHomepage]
enable = true
auto_play = true
slide_speed = 2000
pagination_speed = 1000

[params.features]
enable = true
cols = 3

[params.testimonials]
enable = true
title = "Depoimentos"
subtitle = "Trabalhamos com muitos clientes e sempre gostamos de ouvir que eles saem da colaboração felizes e satisfeitos. Confira o que nossos clientes disseram sobre nós."

[params.carouselTestimonials]
items = 4
auto_play = false
slide_speed = 2000
pagination_speed = 1000

[params.see_more]
enable = true
icon = "far fa-address-card"
title = "Quer saber mais?"
# subtitle = ""
link_url = "contact"
link_text = "Veja como entrar em contato"

[params.clients]
enable = true
title = "Nossos Clientes"
subtitle = ""

[params.carouselCustomers]
items = 6
auto_play = false
slide_speed = 2000
pagination_speed = 1000

[params.widgets]

[menu]

[[menu.main]]
identifier = "menu.home"
name = "Início"
url = "/"
weight = 1

# [[menu.main]]
# identifier = "menu.faq"
# name = "FAQ"
# url = "/faq/"
# weight = 2

[[menu.main]]
identifier = "contact"
name = "Contato"
url = "/contact/"
weight = 3
