baseURL = 'https://hvitoi.github.io/vitoi-eng-seguranca/'
title = 'Vitoi - Engenharia de Segurança do Trabalho'
theme = 'hugo-universal-theme'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'

[params]
style = 'red'
logo = 'img/logo.png'
logo_small = 'img/logo.png'

about_us = "<p>Paellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"

address = """
            <p class="text-uppercase">
                  <strong>Universal Ltd.</strong>
                  <br>13/25 New Avenue
                  <br>Newtown upon River
                  <br>45Y 73J
                  <br>England
                  <br>
                  <strong>Great Britain</strong>
            </p>
            """

[params.widgets]
categories = true
tags = true
search = true

[params.carouselCustomers]
items = 6
auto_play = false
slide_speed = 2000
pagination_speed = 1000

[params.carouselTestimonials]
items = 4
auto_play = false
slide_speed = 2000
pagination_speed = 1000

[params.carouselHomepage]
enable = true
auto_play = true
slide_speed = 2000
pagination_speed = 1000

[params.features]
enable = true
cols = 3

[params.testimonials]
enable = true
title = "Testimonials"
subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
enable = true
icon = "far fa-file-alt"
title = "Do you want to see more?"
subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
link_url = "#"
link_text = "Check other homepages"

[params.clients]
enable = true
title = "Our Clients"
subtitle = ""

[params.recent_posts]
enable = true
title = "From our blog"
subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
hide_summary = false

[params.footer.recent_posts]
enable = true

[menu]

[[menu.main]]
identifier = "menu.home"
name = "Início"
url = "/"
weight = 1

[[menu.main]]
identifier = "menu.faq"
name = "FAQ"
url = "/faq/"
weight = 2

[[menu.main]]
identifier = "contact"
name = "Contato"
url = "/contact/"
weight = 3
